# Generated by Django 3.2.7 on 2021-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Featured', 'Featured'), ('New Arrival', 'New Arrival'), ('Top Rated', 'Top Rated'), ('Best Selling', 'Best Selling'), ('On Sale', 'On Sale')], max_length=50, null=True),
        ),
    ]
