# Generated by Django 3.2.8 on 2021-11-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Featured', 'Featured'), ('New Arrival', 'New Arrival'), ('Top Rated', 'Top Rated'), ('Best Selling', 'Best Selling'), ('On Sale', 'On Sale')], max_length=50, null=True),
        ),
    ]
